### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by JohnGalt999** [MainNerve/NetforceDefender#18]
First I'm very new to this and first time touching any type of Linux.
I've run through the installation and after I run the install and the system reboots I try to run the following and receive the following
tail –f /var/log/netforce_install.log
tail: cannot open '/var/log/netforce_install.log' for reading No such file or directory
tail: no files remaining

Running on Ubuntu server 16.04.1 64bit

**Comment by ThomasdOtreppe** [comment]
Could you paste the exact command used for the installation with the exception of the login/password for email?

I can think of one reason why it didn't create the file: the system already had ethX interfaces and was completely up to date. In this case, it didn't need a reboot. It only create that log files after a reboot.

Could you run the install_checker.sh (in the testing/ directory) and post the results?

**Comment by JohnGalt999** [comment]
I never got that far below is all I've done:
logged in as mnadmin

sudo apt-get install tofrodos git -y
git clone https://github.com/MainNerve/NetforceDefender
cd NetforceDefender
fromdos netforce_install.sh
chmod +x netforce_install.sh
sudo ./netforce_install.sh --install logger

That's it now sitting at a prompt with the error message

**Comment by ThomasdOtreppe** [comment]
What is the error message? Could you paste it here?

**Comment by JohnGalt999** [comment]
Error message:
tail: cannot open '/var/log/netforce_install.log' for reading No such file or directory
tail: no files remaining

I found the NetForceDefender directory and I only find 
netforce_install.sh not netforce_install.log

How do I run the install_checker.sh?  Sorry first time working with Linux

**Comment by ThomasdOtreppe** [comment]
I thought you meant there was an error when running the install command, my bad.

To run the install checker:
```
cd NetforceDefender/testing
fromdos install_checker.sh
sudo bash install_checker.sh
```

**Comment by JohnGalt999** [comment]
When I run it I get 

NetForce Defender/Logger Open source install checker v0.1

-Installed Item: Nothing. Aborting.

**Comment by ThomasdOtreppe** [comment]
OK. What is the output of the installation command you ran?

**Comment by JohnGalt999** [comment]
It ran quickly then rebooted the server, once it came back up I logged back in as mnadmin I just have the prompt waiting for a command

**Comment by ThomasdOtreppe** [comment]
Could you re-run the installation but append `` >logs.txt 2>logs.txt`` at the end of ``sudo bash netforce_install.sh`` and paste logs.txt here so I can see what you did (Don't worry, will not contain any password).

**Comment by ThomasdOtreppe** [comment]
I just fixed a bug related to logger. Update it (``git pull``) then reinstall.

**Comment by JohnGalt999** [comment]
I am reinstalling Ubuntu and going to download the software again since none of the commands are working and I am basically looking at a blinking cursor and only error messages

**Comment by ThomasdOtreppe** [comment]
I'm trying to figure out what you are doing to understand the problem and have trouble understanding what's going on. If you can, ssh in the Ubuntu server from a Windows machine and use PSR (Problem Steps Recorder) to record the steps then upload the resulting files and screenshots (make sure you are not typing any passwords or anything sensitive in there).

**Comment by JohnGalt999** [comment]
I reinstalled and that last command never ran but I can log into the interface now.  
Is the tail command necessary to run?

**Comment by ThomasdOtreppe** [comment]
No, it's not necessary. It's just if you want to follow the installation process.
